server {
    # Listen port NGINX web
    listen 80;
    
    # Titik awal Public Asset laravel
    root /var/www/html/public;

    # Hirarki inisiasi load halaman
    index index.php index.html index.htm;

    # Server Alias
    server_name localhost;

    # Atur lalu lintas folder utama. Secara elegan menyalurkan routing non-file/folder bersih ke index.php
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Atur lalu lintas pemrosesan spesifik PHP (*.php) 
    location ~ \.php$ {
        # Amankan bila dicoba hit script random
        try_files $uri =404;
        
        # Eksekusi fpm melalui konfigurasi konektor FastCGI
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        
        # Kirimkan proses ke service bernama 'app' berdasarkan host local network port 9000!
        fastcgi_pass app:9000;
        
        fastcgi_index index.php;
        include fastcgi_params;
        
        # Mendapatkan nama source file berdasar letak sebenarnya (doc root)
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    # Restriksi akses file/folder tersebunyi spt (.env, .git) agar error 403 / tidak dibaca!
    location ~ /\.ht {
        deny all;
    }
}
