<?php

namespace App\Repositories;

use App\Models\OrderItem;

/**
 * OrderItemRepository
 *
 * Handles database operations for order line items.
 * Separating this from OrderRepository adheres to the single-responsibility
 * principle and allows independent testing of item-level queries.
 */
class OrderItemRepository
{
    /**
     * Create a single order item record.
     *
     * @param  array $data  Mass-assignable order item attributes
     * @return \App\Models\OrderItem
     */
    public function create(array $data)
    {
        return OrderItem::create($data);
    }

    /**
     * Bulk-insert multiple order items.
     *
     * Uses Eloquent's insert() for performance when creating all items
     * in a single order. Note: insert() does not fire model events or
     * mutators, but this is acceptable because OrderItem has no events
     * and UUIDs are pre-generated by the service layer.
     *
     * @param  array $data  Array of item attribute arrays
     * @return bool
     */
    public function insertMany(array $data)
    {
        return OrderItem::insert($data);
    }

    /**
     * Retrieve all items belonging to a specific order.
     *
     * Eager-loads product and service relations to display item
     * details in order views without N+1 queries.
     *
     * @param  string $orderId  UUID of the parent order
     * @return \Illuminate\Database\Eloquent\Collection
     */
    public function getByOrderId(string $orderId)
    {
        return OrderItem::with(['productBrand.product', 'service'])
            ->where('order_id', $orderId)
            ->get();
    }

    /**
     * Delete all items belonging to a specific order.
     *
     * Useful for order cancellation workflows where line items
     * should be removed before the order record itself.
     *
     * @param  string $orderId  UUID of the parent order
     * @return int  Number of deleted records
     */
    public function deleteByOrderId(string $orderId): int
    {
        return OrderItem::where('order_id', $orderId)->delete();
    }
}
